# Generated by Django 4.0 on 2021-12-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.FloatField(default=12),
            preserve_default=False,
        ),
    ]
